config/routes.rb
Rails.application.routes.draw do
  root "articles#index"


  resources :articles do
    resources :comments

 end
#  resources :posts
#  resources :users, only: [:create]
 get '/register', to: 'users#new', as: :user_register

 put '/save_user', to:'users#create', as: :save_user

 get "/users", to: 'users#index'

 get '/signin', to: 'users#signin', as: :signin_user

 post '/login', to:'users#login', as: :login_user

 get '/logout', to:'users#log_out'

 get '/editprofile', to:'users#editprofile'

 patch '/editprofile', to:'users#save_editied_profile', as: :edit_profile


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
 

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  

  belongs_to :article
  
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password
has_many :articles
validates :username, presence: true
validates :email, presence: true, uniqueness: true
validates :password, presence: true, confirmation: true
validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  def current_user
    if session[:user_id]
      @current_user = User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !@current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :current_user
  before_action :check_session, :except => [:show, :index]

  def index
    @articles = Article.order(created_at: :desc).all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = @current_user.articles.new(article_params)
    #@article = Article.new(article_params)
  
    if @article.save
      redirect_to root_path, notice: "article added"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end

  def check_session
    unless session[:user_id]
      flash[:alert] = "You need user account to post something"
      redirect_to signin_user_path


    end
  end

 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  end
  
  def create
    @article = Article.find_by(id: params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user
  def new
    @user = User.new
  end

    def create
      @user = User.new(user_params)
 
      if @user.save
          session[:user_id] = @user.id
          redirect_to new_article_path
      else
        flash[:reg_form_messages] = @user.errors
        redirect_to user_register_path
     
      end
  end

  def signin
    @user = User.new

  end

  def login
    @user = User.find_by(email: params['email'].downcase)
    if @user && @user.authenticate(params['password'])
      session[:user_id] = @user.id 
      redirect_to root_path 
    else
      flash[:alert] = 'Invalid email/password combination'
      redirect_to signin_user_path
    end
  end

  def log_out
    session[:user_id]=nil
    @current_user = nil
    session.destroy
    redirect_to root_path
  end

  def editprofile
    @user = User.find_by(id: @current_user.id)
  end

  def save_editied_profile
    
  #  redirect_to root_path, notice: @current_user.id
  #  redirect_to root_path, notice: update_status if  update_status.update(username: params['username'], email: params['email'])
    if invalid_current_password
      flash[:alert]= "your current password isn't equal to old password"
    elsif  @current_user.update(update_user_params)
        flash[:notice] = "Your page is succesfuly updated"
    else
      flash[:reg_form_messages] = @current_user.errors
    end
    redirect_to edit_profile_path
  end

  

  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def update_user_params
    params.permit(:password, :password_confirmation)
  end
 
  def invalid_current_password
    !@current_user.authenticate(params['current_password'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control",  placeholder: "title"%>
<% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
   
  </div>
  <div class="form-group">
  <%= form.label :body %><br>
   <%= form.text_area :body, class: "form-control", placeholder: "body"%><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <%= form.submit class: "btn btn-primary"%>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
Our blog has <%= @articles.size %> articles and counting!

<%= link_to  "New Article", new_article_path ,  class:"link-primary"%>



<div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
  <% @articles.each do |article| %>


                      <div class="post-preview">
                        <h2 class="post-title"><%= link_to article.title, article%></h2>
                        
                        <p class="post-meta">
                            Posted by
                            <a href="#!"><%=article.user.username%></a>
                            <%=article.created_at%>
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    <!-- Post preview-->
  
  <%end%>

                   
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article, local: true, data: { turbo: false } do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
     <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
     <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<article class="mb-4">

            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                    <h1><%= @article.title %></h1>
                    <h1><%= @article.user.username %></h1>
                    <ul>
<%if session[:user_id] && !session[:user_id]== @article.user.id%>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
   <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li> <%end%>
                  </ul>
                    <hr>
                       <p><%= @article.body %></p>
                       <hr>
                               <h2>Comments(<%=@article.comments.size%>)</h2>

<div>





<div class=" mt-5">

            <div class="  d-flex justify-content-center">

                <div class="col-md-12">
<% unless @article.comments.empty?%>
<% @article.comments.each do |comment| %>



                    <div class="card p-3">

                        <div class="d-flex justify-content-between align-items-center">

                      <div class="user d-flex flex-row align-items-center">

                        <span><small class="font-weight-bold text-primary"><%=comment.commenter%></small> <small class="font-weight-bold"><%=comment.body%></small></span>
                          
                      </div>


                      <small><%=time_ago_in_words(comment.created_at).concat(" ago")%></small>

                      </div>


                      <div class="action d-flex justify-content-between mt-2 align-items-center">
<%# 
                        <div class="reply px-4">
                            <small>Remove</small>
                            <span class="dots"></span>
                            <small>Reply</small>
                            <span class="dots"></span>
                            <small>Translate</small>
                           
                        </div> %>

                        <div class="icons align-items-center">

                            <i class="fa fa-star text-warning"></i>
                            <i class="fa fa-check-circle-o check-icon"></i>
                            
                        </div>
                          
                      </div>


                        
                    </div>


<br>
<% end %>

<% else %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  No comments found
</div>
<% end %>


                    
                </div>
                
            </div>
            
        </div>








</div>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
                           
                    </div>
                </div>
            </div>
        </article>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to "Destroy Comment", [comment.article, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%=render partial:'main/navbar',current_user: @current_user%>
  <% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">  
    <%= flash[:alert] %>
  </div>
<% end %>
 
 
    <%= yield %>
  </body>
</html>

app/views/main/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                
           
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                     <li class="nav-item"> <%= link_to 'Home', articles_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                    <%if session[:user_id] %>
                       <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href='/editprofile'>Hello,<%=@current_user.username%></a></li>
                       <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/logout">Logout</a></li>
                        <%else%>
                       
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="<%=signin_user_path%>">Login</a></li>
                        <li class="nav-item"><%= link_to 'signup', user_register_path, class: "nav-link px-lg-3 py-3 py-lg-4" %></li>
                        <%end%>
                    </ul>
                </div>
            </div>
        </nav>
        <header class="masthead" style="background-image: url(<%=image_path("home-bg.jpg")%>)">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        
                    </div>
                </div>
            </div>
        </header>

app/views/users/editprofile.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Edit Password</p>

                <form action = "<%=edit_profile_path%>", method = "post" class="mx-1 mx-md-4">
                <input type="hidden" name="_method" value="patch" />
          

               
                   <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[current_password]">Current Password</label>
                      <input class="form-control" type="password" id="user[password]" name = "current_password" /><br>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[password]"> Password</label>
                      <input class="form-control" type="password" id="password" name = "password" /><br>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[password_confirmation]"> Confirmation Password</label>
                     <input class="form-control" type="password" id="password_confirmation" name = "password_confirmation" /><br>

                    </div>
                  </div>

                 

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <input type = "submit" value ="Edit Profile" class="btn btn-primary btn-lg"><br>
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> %>

app/views/users/new.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>

                <form action = "/save_user", method = "post" class="mx-1 mx-md-4">
                <input type="hidden" name="_method" value="put" />
          
                  <% unless flash[:reg_form_messages].nil? %>
                   <div class="alert alert-danger" role="alert">
 <% flash[:reg_form_messages].each do |key, msg| %>
                        <%= key.to_s + " " + msg.first.to_s %><br>
                      <% end %>
</div>
                     

                  <% end %>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[username]"> Username</label>
                      <input class="form-control" type="text" id="user[username]" name = "user[username]" /><br>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[email]"> Email</label>
                      <input class="form-control" type="email" id="user[email]" name = "user[email]" /><br>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[password]"> Password</label>
                      <input class="form-control" type="password" id="user[password]" name = "user[password]" /><br>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[password_confirmation]"> Confirmation Password</label>
                     <input class="form-control" type="password" id="user[password_confirmation]" name = "user[password_confirmation]" /><br>

                    </div>
                  </div>

                 

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <input type = "submit" value ="Register" class="btn btn-primary btn-lg"><br>
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> %>

app/views/users/signin.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign in</p>

                <form action = "<%=login_user_path%>", method = "post" class="mx-1 mx-md-4">
                <% if @user.errors.any? %>
                    <div class="alert alert-danger">
                      <% form.object.errors.full_messages.each do |message| %>
                        <div> <%= message %> </div>
                      <% end %>
                    </div>
                  <% end %>
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[email]"> Email</label>
                      <input class="form-control" type="email" id="user[email]" name = "email" /><br>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <label class="form-label" for ="user[password]"> Password</label>
                      <input class="form-control" type="password" id="user[password]" name = "password" /><br>
                    </div>
                  </div>
                  
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <input type = "submit" value ="Signin" class="btn btn-primary btn-lg"><br>
                  </div>

                </form>

              </div>
             
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>